/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frames;

import com.DAO.BatchDao;
import com.DAO.FeesDao;
import com.DAO.StudentDao;
import com.DAOIMp.BatchDaoImp;
import com.DAOIMp.FeesDaoImp;
import com.DAOIMp.StudentDaoImp;
import com.pojos.Batch;
import com.pojos.Fees;
import com.pojos.Student;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dell
 */
public class StudentFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentFrame
     */
    BatchDao batchDao = new BatchDaoImp();
    FeesDao feesDao = new FeesDaoImp();
    StudentDao studentDAO = new StudentDaoImp();
    DefaultTableModel tableModel;

    public StudentFrame() {
        initComponents();
        fillFeesCombo();
        fillBatchCombo();
        fillCountryTable();

    }
     private void fillCountryTable() {
        Object columnNames[] = {"std_id","name","department","PhoneNo","Address","date_of_addmition","Batch_id","fees_id"};
        tableModel = new DefaultTableModel(columnNames, 0);
        List<Student> list = studentDAO.getStudents();
        for (Student s : list) {
           Batch b=batchDao.getBatchById(s.getBatch().getBatch_id());
           Fees f=feesDao.getFeesById(s.getFees().getFees_id());
            Object rowData[] = {s.getStd_id(),s.getName(),s.getDepartment(),s.getPhone_No(),s.getAddress(),s.getDate_of_addmition(),b.getBatch_name(),f.getFees()};
            tableModel.addRow(rowData);
            StudentTable.setModel(tableModel);
        }
    }

    public void fillBatchCombo() {
        List<Batch> list = batchDao.getAllBatches();
        batchCombo.addItem("--Select Batch--");
        for (Batch db : list) {
            batchCombo.addItem(db.getBatch_name());
        }
    }

    public void fillFeesCombo() {
        List<Fees> list = feesDao.getAllFees();
        feesCombo.addItem("--Select Fees--");
        for (Fees db : list) {
            feesCombo.addItem(db.getFees());
        }
    }
    public void filterContactList(String query) {
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(tableModel);
        StudentTable.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(query));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stdNameField = new javax.swing.JTextField();
        deptField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        dateFields = new org.jdesktop.swingx.JXDatePicker();
        batchCombo = new javax.swing.JComboBox();
        feesCombo = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT TABLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 56, -1, -1));

        jLabel2.setText("Student Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 142, 80, -1));

        jLabel3.setText("Department");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 184, 70, -1));

        jLabel4.setText("Phone No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 142, 70, -1));

        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 184, -1, -1));

        jLabel6.setText("Date of Addmition");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setText("Batch");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 272, 53, -1));

        jLabel8.setText("Fees");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 272, -1, -1));
        getContentPane().add(stdNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 139, 153, -1));
        getContentPane().add(deptField, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 181, 153, -1));
        getContentPane().add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 139, 153, -1));

        addressField.setColumns(20);
        addressField.setRows(5);
        jScrollPane1.setViewportView(addressField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 181, -1, 59));

        dateFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldsActionPerformed(evt);
            }
        });
        getContentPane().add(dateFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 218, 153, -1));

        getContentPane().add(batchCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 269, 153, -1));
        getContentPane().add(feesCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 269, 170, -1));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(StudentTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 750, 158));

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addGap(16, 16, 16)
                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, 180));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BackBtn.setText("BACK");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel9.setText("Search");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 230, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here

        String std_name = stdNameField.getText();

        String dept = deptField.getText();
        String Address = addressField.getText();
        Integer PhoneNo = Integer.parseInt(phoneField.getText());
        System.out.println("dateee " + dateFields.getDate());
       // SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
       // formater.format(dateFields.getDate());
       // Date date = (Date) dateFields.getDate();

        String dist = batchCombo.getSelectedItem().toString();
        Integer batch_Id = batchDao.getBatchByName(dist);
        Integer amount =  (Integer) feesCombo.getSelectedItem();
        Integer fees_id = feesDao.getFeesIdByFees(amount);
        Batch b = new Batch();
        b.setBatch_id(batch_Id);
        Fees f = new Fees();
        f.setFees_id(fees_id);

        Student s = new Student();

        s.setName(std_name);

        s.setAddress(Address);
        s.setPhone_No(PhoneNo);
        s.setDate_of_addmition(dateFields.getDate());
        s.setBatch(b);
        s.setFees(f);
        s.setDepartment(dept);
        // System.out.println("dateee "+);

        int row = studentDAO.addStudent(s);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Added Sucessfully");
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
        fillCountryTable();


    }//GEN-LAST:event_addBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        stdNameField.setText("");
        deptField.setText("");
        addressField.setText("");
        phoneField.setText(null);
        dateFields.setDate(null);
        batchCombo.setSelectedIndex(0);
        feesCombo.setSelectedIndex(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMouseClicked
        // TODO add your handling code here:
        Integer id = (Integer) StudentTable.getValueAt(StudentTable.getSelectedRow(), 0);
        Student s=studentDAO.getStudentById(id);
        stdNameField.setText(s.getName());
        deptField.setText(s.getDepartment());
        addressField.setText(s.getAddress());
        phoneField.setText(String.valueOf(s.getPhone_No()));
        dateFields.setDate(s.getDate_of_addmition());
       Batch batch=batchDao.getBatchById(s.getBatch().getBatch_id());
       batchCombo.setSelectedItem(batch.getBatch_name());
       Fees f=feesDao.getFeesById(s.getFees().getFees_id());
       feesCombo.setSelectedItem(f.getFees());
        
       
        
                                          
    }//GEN-LAST:event_StudentTableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        Integer id = (Integer) StudentTable.getValueAt(StudentTable.getSelectedRow(), 0);
        Student s= studentDAO.getStudentById(id);
        String std_name = stdNameField.getText();

        String dept = deptField.getText();
        String Address = addressField.getText();
        Integer PhoneNo = Integer.parseInt(phoneField.getText());
        System.out.println("dateee " + dateFields.getDate());
       // SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
       // formater.format(dateFields.getDate());
       // Date date = (Date) dateFields.getDate();

        String dist = batchCombo.getSelectedItem().toString();
        Integer batch_Id = batchDao.getBatchByName(dist);
        Integer amount = (Integer) feesCombo.getSelectedItem();
        Integer fees_id = feesDao.getFeesIdByFees(amount);
        Batch b = new Batch();
        b.setBatch_id(batch_Id);
        Fees f = new Fees();
        f.setFees_id(fees_id);
        s.setName(std_name);
        s.setAddress(Address);
        s.setPhone_No(PhoneNo);
        s.setDate_of_addmition(dateFields.getDate());
        s.setBatch(b);
        s.setFees(f);
        s.setDepartment(dept);
        // System.out.println("dateee "+);

         studentDAO.updateStudent(s);
         fillCountryTable();
        

    }//GEN-LAST:event_updateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        Integer id = (Integer) StudentTable.getValueAt(StudentTable.getSelectedRow(), 0);
        studentDAO.deleteStudent(id);
        System.out.println("Deleted");
        tableModel.removeRow(StudentTable.getSelectedRow());
        StudentTable.clearSelection();
        fillCountryTable();
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void dateFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldsActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        MainFrame m=new MainFrame();
        m.setVisible(true);
        this.dispose();
        
        
                
    }//GEN-LAST:event_BackBtnActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        filterContactList(jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea addressField;
    private javax.swing.JComboBox batchCombo;
    private org.jdesktop.swingx.JXDatePicker dateFields;
    private javax.swing.JTextField deptField;
    private javax.swing.JComboBox feesCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField stdNameField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
